[workspace]
resolver = "2"
members = ["crates/*", "hal/*"]

[workspace.package]
publish = false
edition = "2024"
license = "MIT"
authors = ["Kira"]
repository = "https://github.com/KiraCoding/hai"

[profile.release]
codegen-units = 1
lto = true
